class StaticData {
  static const String apiKey = '027ba9368eb64793820e96dc6c8a3d23';
  static const List<String> category = [
    'all',
    "business",
    "entertainment",
    "general",
    "health",
    "science",
    "sports",
    "technology",
  ];
  static const List<Map<String, String>> country = [
    {"country_code": "ar", "country_name": "Argentina"},
    {"country_code": "at", "country_name": "Austria"},
    {"country_code": "au", "country_name": "Australia"},
    {"country_code": "be", "country_name": "Belgium"},
    {"country_code": "bg", "country_name": "Bulgaria"},
    {"country_code": "br", "country_name": "Brazil"},
    {"country_code": "ca", "country_name": "Canada"},
    {"country_code": "ch", "country_name": "Switzerland"},
    {"country_code": "cn", "country_name": "China"},
    {"country_code": "co", "country_name": "Colombia"},
    {"country_code": "cu", "country_name": "Cuba"},
    {"country_code": "cz", "country_name": "Czech Republic"},
    {"country_code": "de", "country_name": "Germany"},
    {"country_code": "eg", "country_name": "Egypt"},
    {"country_code": "fr", "country_name": "France"},
    {"country_code": "gb", "country_name": "United Kingdom"},
    {"country_code": "gr", "country_name": "Greece"},
    {"country_code": "hk", "country_name": "Hong Kong"},
    {"country_code": "hu", "country_name": "Hungary"},
    {"country_code": "id", "country_name": "Indonesia"},
    {"country_code": "ie", "country_name": "Ireland"},
    {"country_code": "il", "country_name": "Israel"},
    {"country_code": "in", "country_name": "India"},
    {"country_code": "it", "country_name": "Italy"},
    {"country_code": "jp", "country_name": "Japan"},
    {"country_code": "kr", "country_name": "South Korea"},
    {"country_code": "lt", "country_name": "Lithuania"},
    {"country_code": "lv", "country_name": "Latvia"},
    {"country_code": "ma", "country_name": "Morocco"},
    {"country_code": "mx", "country_name": "Mexico"},
    {"country_code": "my", "country_name": "Malaysia"},
    {"country_code": "ng", "country_name": "Nigeria"},
    {"country_code": "nl", "country_name": "Netherlands"},
    {"country_code": "no", "country_name": "Norway"},
    {"country_code": "pl", "country_name": "Poland"},
    {"country_code": "pt", "country_name": "Portugal"},
    {"country_code": "ro", "country_name": "Romania"},
    {"country_code": "ru", "country_name": "Russia"},
    {"country_code": "sa", "country_name": "Saudi Arabia"},
    {"country_code": "sg", "country_name": "Singapore"},
    {"country_code": "sk", "country_name": "Slovakia"},
    {"country_code": "si", "country_name": "Slovenia"},
    {"country_code": "th", "country_name": "Thailand"},
    {"country_code": "tr", "country_name": "Turkey"},
    {"country_code": "tw", "country_name": "Taiwan"},
    {"country_code": "ua", "country_name": "Ukraine"},
    {"country_code": "us", "country_name": "United States"},
    {"country_code": "ve", "country_name": "Venezuela"},
    {"country_code": "za", "country_name": "South Africa"},
    {"country_code": "ae", "country_name": "United Arab Emirates"},
  ];
}
